id: ACC2A0DD4
title: 'BA: Proto-BA (Buddhanāmanirdeśa)'
type: translation
pechas:
- IEAA119D0
- ICCE94FF3
- I9E881408
- I568A43EB
source_metadata:
  languages:
  - sa
  - bo
  - zh
  datatype: PlainText
  created_at: 2023-02-09 14:40:22.001811
  last_modified_at: 2023-02-09 14:40:22.001824
alignment_to_base:
  IEAA119D0/1C33: 4BB1
  ICCE94FF3/CEDA: 4BB1
  I9E881408/ADF2: 4BB1
  I568A43EB/9BA6: 4BB1
